// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmvn_rcpp
double dmvn_rcpp(const arma::rowvec& x, const arma::rowvec& mean, const arma::mat& sigma, bool logd);
RcppExport SEXP _mcmcpackage_dmvn_rcpp(SEXP xSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP logdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type logd(logdSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvn_rcpp(x, mean, sigma, logd));
    return rcpp_result_gen;
END_RCPP
}
// rmvn_rcpp
arma::mat rmvn_rcpp(const int n, const arma::vec& mean, const arma::mat& sigma);
RcppExport SEXP _mcmcpackage_rmvn_rcpp(SEXP nSEXP, SEXP meanSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvn_rcpp(n, mean, sigma));
    return rcpp_result_gen;
END_RCPP
}
// rinvgamma_rcpp
double rinvgamma_rcpp(double a, double b);
RcppExport SEXP _mcmcpackage_rinvgamma_rcpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rinvgamma_rcpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// init_cpp
Rcpp::List init_cpp(int Q, int S, int K, int L, int I, double h_1, double h_2);
RcppExport SEXP _mcmcpackage_init_cpp(SEXP QSEXP, SEXP SSEXP, SEXP KSEXP, SEXP LSEXP, SEXP ISEXP, SEXP h_1SEXP, SEXP h_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type I(ISEXP);
    Rcpp::traits::input_parameter< double >::type h_1(h_1SEXP);
    Rcpp::traits::input_parameter< double >::type h_2(h_2SEXP);
    rcpp_result_gen = Rcpp::wrap(init_cpp(Q, S, K, L, I, h_1, h_2));
    return rcpp_result_gen;
END_RCPP
}
// update_alpha_cpp
arma::mat update_alpha_cpp(const arma::cube& beta, const arma::mat& omega, const arma::vec& sigma2, const arma::cube& data_index, const arma::cube& y, const arma::field<arma::cube>& B, const arma::field<arma::cube>& Z, const arma::vec& g, const arma::cube& Z_sum, const arma::mat& V_alpha_inv, const arma::vec& V_alpha_inv_mu_alpha, int K, int Q, int S, int I, int J_max);
RcppExport SEXP _mcmcpackage_update_alpha_cpp(SEXP betaSEXP, SEXP omegaSEXP, SEXP sigma2SEXP, SEXP data_indexSEXP, SEXP ySEXP, SEXP BSEXP, SEXP ZSEXP, SEXP gSEXP, SEXP Z_sumSEXP, SEXP V_alpha_invSEXP, SEXP V_alpha_inv_mu_alphaSEXP, SEXP KSEXP, SEXP QSEXP, SEXP SSEXP, SEXP ISEXP, SEXP J_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Z_sum(Z_sumSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V_alpha_inv(V_alpha_invSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type V_alpha_inv_mu_alpha(V_alpha_inv_mu_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type I(ISEXP);
    Rcpp::traits::input_parameter< int >::type J_max(J_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(update_alpha_cpp(beta, omega, sigma2, data_index, y, B, Z, g, Z_sum, V_alpha_inv, V_alpha_inv_mu_alpha, K, Q, S, I, J_max));
    return rcpp_result_gen;
END_RCPP
}
// update_beta_cpp
arma::cube update_beta_cpp(const arma::mat& alpha, const arma::cube& beta, const arma::mat& omega, const arma::vec& sigma2, const arma::field<arma::cube>& B, const arma::field<arma::cube>& Z, const arma::vec& g, const arma::cube& y, const arma::field<arma::cube>& B_sum, const arma::cube& B_sum_0, const arma::mat& V_beta_inv, const arma::vec& V_beta_inv_mu_beta, const arma::cube& data_index, int K, int Q, int L, int I, int J_max);
RcppExport SEXP _mcmcpackage_update_beta_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP omegaSEXP, SEXP sigma2SEXP, SEXP BSEXP, SEXP ZSEXP, SEXP gSEXP, SEXP ySEXP, SEXP B_sumSEXP, SEXP B_sum_0SEXP, SEXP V_beta_invSEXP, SEXP V_beta_inv_mu_betaSEXP, SEXP data_indexSEXP, SEXP KSEXP, SEXP QSEXP, SEXP LSEXP, SEXP ISEXP, SEXP J_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B_sum(B_sumSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type B_sum_0(B_sum_0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V_beta_inv(V_beta_invSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type V_beta_inv_mu_beta(V_beta_inv_mu_betaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type I(ISEXP);
    Rcpp::traits::input_parameter< int >::type J_max(J_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(update_beta_cpp(alpha, beta, omega, sigma2, B, Z, g, y, B_sum, B_sum_0, V_beta_inv, V_beta_inv_mu_beta, data_index, K, Q, L, I, J_max));
    return rcpp_result_gen;
END_RCPP
}
// logpost_omega_cpp
double logpost_omega_cpp(int i, const arma::rowvec& omega_i, const arma::mat& alpha, const arma::cube& beta, const arma::vec& sigma2, const arma::mat& Sigma_omega, const arma::cube& y, const arma::field<arma::cube>& Z, const arma::field<arma::cube>& B, const arma::vec& g, const arma::cube& data_index, int K, int Q, int J_max);
RcppExport SEXP _mcmcpackage_logpost_omega_cpp(SEXP iSEXP, SEXP omega_iSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP sigma2SEXP, SEXP Sigma_omegaSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP BSEXP, SEXP gSEXP, SEXP data_indexSEXP, SEXP KSEXP, SEXP QSEXP, SEXP J_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type omega_i(omega_iSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_omega(Sigma_omegaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type J_max(J_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(logpost_omega_cpp(i, omega_i, alpha, beta, sigma2, Sigma_omega, y, Z, B, g, data_index, K, Q, J_max));
    return rcpp_result_gen;
END_RCPP
}
// update_omega_cpp
arma::mat update_omega_cpp(const arma::mat& alpha, const arma::cube& beta, const arma::mat& omega, const arma::vec& sigma2, const arma::mat& Sigma_omega, const arma::cube& y, const arma::field<arma::cube>& Z, const arma::field<arma::cube>& B, const arma::vec& g, const arma::cube& data_index, int K, int Q, int J_max);
RcppExport SEXP _mcmcpackage_update_omega_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP omegaSEXP, SEXP sigma2SEXP, SEXP Sigma_omegaSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP BSEXP, SEXP gSEXP, SEXP data_indexSEXP, SEXP KSEXP, SEXP QSEXP, SEXP J_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_omega(Sigma_omegaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type J_max(J_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(update_omega_cpp(alpha, beta, omega, sigma2, Sigma_omega, y, Z, B, g, data_index, K, Q, J_max));
    return rcpp_result_gen;
END_RCPP
}
// logpost_Sigma_omega_cpp
double logpost_Sigma_omega_cpp(const arma::mat& Sigma_omega, const arma::mat& omega);
RcppExport SEXP _mcmcpackage_logpost_Sigma_omega_cpp(SEXP Sigma_omegaSEXP, SEXP omegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_omega(Sigma_omegaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    rcpp_result_gen = Rcpp::wrap(logpost_Sigma_omega_cpp(Sigma_omega, omega));
    return rcpp_result_gen;
END_RCPP
}
// update_Sigma_omega_cpp
arma::mat update_Sigma_omega_cpp(const arma::mat& omega, const arma::mat& Sigma_omega);
RcppExport SEXP _mcmcpackage_update_Sigma_omega_cpp(SEXP omegaSEXP, SEXP Sigma_omegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_omega(Sigma_omegaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Sigma_omega_cpp(omega, Sigma_omega));
    return rcpp_result_gen;
END_RCPP
}
// update_sigma2_cpp
arma::vec update_sigma2_cpp(arma::mat& alpha, arma::cube& beta, arma::mat& omega, const arma::cube& y, const arma::field<arma::cube>& Z, const arma::field<arma::cube>& B, const arma::cube& data_index, const arma::vec& g, double h_1, double h_2, int K, int J_max, int I, int Q);
RcppExport SEXP _mcmcpackage_update_sigma2_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP omegaSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP BSEXP, SEXP data_indexSEXP, SEXP gSEXP, SEXP h_1SEXP, SEXP h_2SEXP, SEXP KSEXP, SEXP J_maxSEXP, SEXP ISEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type h_1(h_1SEXP);
    Rcpp::traits::input_parameter< double >::type h_2(h_2SEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type J_max(J_maxSEXP);
    Rcpp::traits::input_parameter< int >::type I(ISEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(update_sigma2_cpp(alpha, beta, omega, y, Z, B, data_index, g, h_1, h_2, K, J_max, I, Q));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_update
List mcmc_update(const List& orig, const arma::cube& data_index, const arma::cube& y, const arma::field<arma::cube>& B_cpp, const arma::field<arma::cube>& Z_cpp, const arma::vec& g_cpp, const arma::cube& Z_sum, const arma::mat& V_alpha_inv, const arma::vec& V_alpha_inv_mu_alpha, const int K, const int Q, const int S, const int I, const int J_max, const arma::field<arma::cube>& B_sum_cpp, const arma::cube& B_sum_0, const arma::mat& V_beta_inv, const arma::vec& V_beta_inv_mu_beta, const int L, const double h_1, const double h_2);
RcppExport SEXP _mcmcpackage_mcmc_update(SEXP origSEXP, SEXP data_indexSEXP, SEXP ySEXP, SEXP B_cppSEXP, SEXP Z_cppSEXP, SEXP g_cppSEXP, SEXP Z_sumSEXP, SEXP V_alpha_invSEXP, SEXP V_alpha_inv_mu_alphaSEXP, SEXP KSEXP, SEXP QSEXP, SEXP SSEXP, SEXP ISEXP, SEXP J_maxSEXP, SEXP B_sum_cppSEXP, SEXP B_sum_0SEXP, SEXP V_beta_invSEXP, SEXP V_beta_inv_mu_betaSEXP, SEXP LSEXP, SEXP h_1SEXP, SEXP h_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type orig(origSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B_cpp(B_cppSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z_cpp(Z_cppSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g_cpp(g_cppSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Z_sum(Z_sumSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V_alpha_inv(V_alpha_invSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type V_alpha_inv_mu_alpha(V_alpha_inv_mu_alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const int >::type S(SSEXP);
    Rcpp::traits::input_parameter< const int >::type I(ISEXP);
    Rcpp::traits::input_parameter< const int >::type J_max(J_maxSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B_sum_cpp(B_sum_cppSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type B_sum_0(B_sum_0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V_beta_inv(V_beta_invSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type V_beta_inv_mu_beta(V_beta_inv_mu_betaSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const double >::type h_1(h_1SEXP);
    Rcpp::traits::input_parameter< const double >::type h_2(h_2SEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_update(orig, data_index, y, B_cpp, Z_cpp, g_cpp, Z_sum, V_alpha_inv, V_alpha_inv_mu_alpha, K, Q, S, I, J_max, B_sum_cpp, B_sum_0, V_beta_inv, V_beta_inv_mu_beta, L, h_1, h_2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mcmcpackage_dmvn_rcpp", (DL_FUNC) &_mcmcpackage_dmvn_rcpp, 4},
    {"_mcmcpackage_rmvn_rcpp", (DL_FUNC) &_mcmcpackage_rmvn_rcpp, 3},
    {"_mcmcpackage_rinvgamma_rcpp", (DL_FUNC) &_mcmcpackage_rinvgamma_rcpp, 2},
    {"_mcmcpackage_init_cpp", (DL_FUNC) &_mcmcpackage_init_cpp, 7},
    {"_mcmcpackage_update_alpha_cpp", (DL_FUNC) &_mcmcpackage_update_alpha_cpp, 16},
    {"_mcmcpackage_update_beta_cpp", (DL_FUNC) &_mcmcpackage_update_beta_cpp, 18},
    {"_mcmcpackage_logpost_omega_cpp", (DL_FUNC) &_mcmcpackage_logpost_omega_cpp, 14},
    {"_mcmcpackage_update_omega_cpp", (DL_FUNC) &_mcmcpackage_update_omega_cpp, 13},
    {"_mcmcpackage_logpost_Sigma_omega_cpp", (DL_FUNC) &_mcmcpackage_logpost_Sigma_omega_cpp, 2},
    {"_mcmcpackage_update_Sigma_omega_cpp", (DL_FUNC) &_mcmcpackage_update_Sigma_omega_cpp, 2},
    {"_mcmcpackage_update_sigma2_cpp", (DL_FUNC) &_mcmcpackage_update_sigma2_cpp, 14},
    {"_mcmcpackage_mcmc_update", (DL_FUNC) &_mcmcpackage_mcmc_update, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_mcmcpackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
